// <auto-generated />
using FizzBuzz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FizzBuzz.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FizzBuzz.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Output = "1"
                        },
                        new
                        {
                            Id = 2,
                            Output = "2"
                        },
                        new
                        {
                            Id = 3,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 4,
                            Output = "4"
                        },
                        new
                        {
                            Id = 5,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 6,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 7,
                            Output = "7"
                        },
                        new
                        {
                            Id = 8,
                            Output = "8"
                        },
                        new
                        {
                            Id = 9,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 10,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 11,
                            Output = "11"
                        },
                        new
                        {
                            Id = 12,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 13,
                            Output = "13"
                        },
                        new
                        {
                            Id = 14,
                            Output = "14"
                        },
                        new
                        {
                            Id = 15,
                            Output = "FizzBuzz"
                        },
                        new
                        {
                            Id = 16,
                            Output = "16"
                        },
                        new
                        {
                            Id = 17,
                            Output = "17"
                        },
                        new
                        {
                            Id = 18,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 19,
                            Output = "19"
                        },
                        new
                        {
                            Id = 20,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 21,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 22,
                            Output = "22"
                        },
                        new
                        {
                            Id = 23,
                            Output = "23"
                        },
                        new
                        {
                            Id = 24,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 25,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 26,
                            Output = "26"
                        },
                        new
                        {
                            Id = 27,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 28,
                            Output = "28"
                        },
                        new
                        {
                            Id = 29,
                            Output = "29"
                        },
                        new
                        {
                            Id = 30,
                            Output = "FizzBuzz"
                        },
                        new
                        {
                            Id = 31,
                            Output = "31"
                        },
                        new
                        {
                            Id = 32,
                            Output = "32"
                        },
                        new
                        {
                            Id = 33,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 34,
                            Output = "34"
                        },
                        new
                        {
                            Id = 35,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 36,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 37,
                            Output = "37"
                        },
                        new
                        {
                            Id = 38,
                            Output = "38"
                        },
                        new
                        {
                            Id = 39,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 40,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 41,
                            Output = "41"
                        },
                        new
                        {
                            Id = 42,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 43,
                            Output = "43"
                        },
                        new
                        {
                            Id = 44,
                            Output = "44"
                        },
                        new
                        {
                            Id = 45,
                            Output = "FizzBuzz"
                        },
                        new
                        {
                            Id = 46,
                            Output = "46"
                        },
                        new
                        {
                            Id = 47,
                            Output = "47"
                        },
                        new
                        {
                            Id = 48,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 49,
                            Output = "49"
                        },
                        new
                        {
                            Id = 50,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 51,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 52,
                            Output = "52"
                        },
                        new
                        {
                            Id = 53,
                            Output = "53"
                        },
                        new
                        {
                            Id = 54,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 55,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 56,
                            Output = "56"
                        },
                        new
                        {
                            Id = 57,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 58,
                            Output = "58"
                        },
                        new
                        {
                            Id = 59,
                            Output = "59"
                        },
                        new
                        {
                            Id = 60,
                            Output = "FizzBuzz"
                        },
                        new
                        {
                            Id = 61,
                            Output = "61"
                        },
                        new
                        {
                            Id = 62,
                            Output = "62"
                        },
                        new
                        {
                            Id = 63,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 64,
                            Output = "64"
                        },
                        new
                        {
                            Id = 65,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 66,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 67,
                            Output = "67"
                        },
                        new
                        {
                            Id = 68,
                            Output = "68"
                        },
                        new
                        {
                            Id = 69,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 70,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 71,
                            Output = "71"
                        },
                        new
                        {
                            Id = 72,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 73,
                            Output = "73"
                        },
                        new
                        {
                            Id = 74,
                            Output = "74"
                        },
                        new
                        {
                            Id = 75,
                            Output = "FizzBuzz"
                        },
                        new
                        {
                            Id = 76,
                            Output = "76"
                        },
                        new
                        {
                            Id = 77,
                            Output = "77"
                        },
                        new
                        {
                            Id = 78,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 79,
                            Output = "79"
                        },
                        new
                        {
                            Id = 80,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 81,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 82,
                            Output = "82"
                        },
                        new
                        {
                            Id = 83,
                            Output = "83"
                        },
                        new
                        {
                            Id = 84,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 85,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 86,
                            Output = "86"
                        },
                        new
                        {
                            Id = 87,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 88,
                            Output = "88"
                        },
                        new
                        {
                            Id = 89,
                            Output = "89"
                        },
                        new
                        {
                            Id = 90,
                            Output = "FizzBuzz"
                        },
                        new
                        {
                            Id = 91,
                            Output = "91"
                        },
                        new
                        {
                            Id = 92,
                            Output = "92"
                        },
                        new
                        {
                            Id = 93,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 94,
                            Output = "94"
                        },
                        new
                        {
                            Id = 95,
                            Output = "Buzz"
                        },
                        new
                        {
                            Id = 96,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 97,
                            Output = "97"
                        },
                        new
                        {
                            Id = 98,
                            Output = "98"
                        },
                        new
                        {
                            Id = 99,
                            Output = "Fizz"
                        },
                        new
                        {
                            Id = 100,
                            Output = "Buzz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
